config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root "welcome#index"
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
    
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  after_create :send_favorite_emails

  private

  def send_favorite_emails
    post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy

  #relates the models and allows us to call post.votes.  dependent: :destory ensures that votes are destroyed when their parent post is deleted
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  default_scope { order('rank DESC') }

  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/sponsored_post.rb
class SponsoredPost < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase if email.present? }
  before_save { self.role ||= :member }

  validates :name, length: {minimum: 1, maximum:100 }, presence: true

  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 254 }

  has_secure_password

  enum role: [:member, :admin]

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value,
    inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private

  def update_post
    post.update_rank
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_sign_in, except: :show

  before_action :authorize_user, except: [:show, :new, :create]

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user

    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end


  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)

    if @post.save
      flash[:notice] = "Post was updated"
      redirect_to [@post.topic, @post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "\"#{@post.title}\" was deleted successfully."
      redirect_to @post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

  def authorize_user
    post = Post.find(params[:id])

    unless current_user == post.user || current_user.admin? || current_user.moderator?
      flash[:alert] = "You must be an admin to do that."
      redirect_to [post.topic, post]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new
    @user.name = params[:user][:name]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save
      flash[:notice] = "Welcome to Bloccit #{@user.name}!"
      create_session(@user)
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error creating your account.  Please try again."
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.visible_to(current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?
    content_tag :div, capture(&block), class: css_class
  end

  def avatar_url(user)
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
    current_user && (current_user == comment.user || current_user.admin?)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def user_has_post?
    @user.posts.count >= 1
  end

  def user_has_comments?
    @user.comments.count >=1
  end

  def user_has_favorites?
    @user.favorites.count >=1
  end

end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>
  <%= form_group_tag(post.errors[:body]) do %>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>
    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div class="media">
  <%= render partial: 'votes/voting', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, topic_post_path(post.topic, post) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<div class = "row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
      <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
    </div>
  </div>

app/views/posts/new.html.erb
<h1> New Post </h1>

<div class = "row">
  <div class="col-md-4">
    <p>Guidelines for posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hastags will get you banned.</li>
    </ul>
  </div>
  <div class = "col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
    </div>
  </div>

app/views/posts/show.html.erb
<div>
  <%= render partial: 'votes/voting', locals: { post: @post } %>
  <h1>
    <%= @post.title %> <br>
    <small>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
    </small>
  </h1>
</div>

<div class="row">
  <div class="col-md-8">
    <p><%= @post.body %></p>
    <div>
      <h3>Comments</h3>
      <%= render @post.comments %>
    </div>
    <% if current_user %>
      <%= render 'comments/form', comment: Comment.new, post: @post %>
    <% end %>
  </div>
  <% if user_is_authorized_for_post?(@post) %>
    <div class="col-md-4">
      <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
      <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
    </div>
  <% end %>
  <div class="col-md-4">
    <h3>
      <%= pluralize(@post.points, 'point') %>
      <div>
        <small>
          <%= pluralize(@post.up_votes, 'up vote') %>,
          <%= pluralize(@post.down_votes, 'down vote') %>
        </small>
      </div>
    </h3>
    <% if current_user %>
      <%= render partial: 'favorites/favorite', locals: { post: @post } %>
    <% end %>
  </div>
</div>

app/views/users/confirm.html.erb
<h1> Sign Up Confirmation </h1>
<h3>Are you sure these values are correct?</h2>
<br>
<br>
<h3>
  <p>
    Email: <%= @user.email %>
  </p>
  <p>
    Name: <%= @user.name %>
  </p>
</h3>

<div class="row">
  <div class="col-md-4", style="width: auto;">
    <%= button_to "Yes", { controller: :users, action: :create, params: params}, class: 'btn btn-success'  %>
  </div>
  <div class="col-md-4", style="width: auto;">
    <%= button_to "No", { controller: :users, action: :new}, class: 'btn btn-failure', method: :get  %>
  </div>
</div>

app/views/users/new.html.erb
<h2> Sign Up </h2>

<div class= "row">
  <div class="col-md-8">
    <%= form_for @user, url: { action: :confirm } do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= form_group_tag(@user.errors[:name]) do %>
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
      <% end %>
      <%= form_group_tag(@user.errors[:email]) do %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
      <% end %>
      <%= form_group_tag(@user.errors[:password]) do %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
      <% end %>
      <%= form_group_tag(@user.errors[:password_confirmation]) do %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form_control', placeholder: "Enter password confirmation" %>
      <% end %>
      <div class="form-group">
        <%= f.submit "Sign up", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class"col-md-8">
    <div class="media">
      <br />
      <% avatar_url = @user.avatar_url(128) %>
      <% if avatar_url %>
        <div class="media-left">
          <%= image_tag avatar_url, class: 'media-object' %>
        </div>
      <% end %>
      <div class="media-body">
        <h2 class="media-heading"><%= @user.name %></h2>
        <small>
          <%= pluralize(@user.posts.count, 'post') %>,
          <%= pluralize(@user.comments.count, 'comment') %>
        </small>
      </div>
    </div>
  </div>
</div>

<% if user_has_post? %>
  <h2>Posts</h2>
  <%= render @user.posts %>
<% else %>
  <h4> <%= "#{@user.name} has not submitted any posts yet." %> </h4>
<% end %>

<% if user_has_comments? %>
  <h2>Comments</h2>
  <%= render @user.comments %>
<% else %>
  <h4> <%= "#{@user.name} has not submitted any comments yet." %> </h4>
<% end %>

<h2>Favorites</h2>
<% if user_has_favorites? %>
  <% @user.favorites.each do |favorite| %>
    <li><%= favorite.post.title %></li>
  <% end %>
<% else %>
  <p><%= @user.name %> has not favorited any posts.</p>
<% end %>